### ISSUE TITLE
Inclusion in Raven.js 1.1?

### ISSUE THREAD

**Issue by mattrobenolt** [gdi2290/angular-raven#1]
Would you be interested in getting this plugin included to be distributed with raven.js core?

See: https://github.com/getsentry/raven-js/tree/master/plugins & http://ravenjs.com

**Comment by henry74** [comment]
Did this happen?

**Comment by mattrobenolt** [comment]
Yeah, see: https://github.com/getsentry/raven-js/blob/master/plugins/angular.js

**Comment by henry74** [comment]
How does one use the plug-in? Is it better than installing angular raven
through bower?

**Comment by mattrobenolt** [comment]
@henry74 not entirely sure what you're asking. The plugin just needs to be included somewhere on the page. I'm not super familiar with bower, but for raven-js, you can include a script tag like: `<script src="//cdn.ravenjs.com/1.1.18/angular,jquery,native/raven.min.js"></script>` and that includes the plugin.

Also, I have 0 affiliation with this repository and the `angular-raven` module, so I can't speak to this.

**Comment by henry74** [comment]
@mattrobenolt Thanks, Matt.  The code in the plugin is different from what is provided by angular-raven so I was confused by the connection, but you're saying they aren't connected outside of just copying the code here into a plugin.

**Comment by mattrobenolt** [comment]
Yeah, these projects are not linked or affiliated in any way at this point.
