### ISSUE TITLE
Exception causes error in sentry

### ISSUE THREAD

**Issue by adamduren** [gdi2290/angular-raven#12]
When trying to integrate the library I've noticed the following issue and it appears to be around [this](https://github.com/gdi2290/angular-raven/blob/master/angular-raven.js#L133) line of code. `cause` passed in from angular is a string and the exception is an `Error` instance. The second argument of  captureException expects an object and not a string. This results in the following log in sentry.

![sentry error](https://cloud.githubusercontent.com/assets/581097/9750265/5eaeb3b2-5663-11e5-8a96-22bd8214799a.PNG)

There's an entry for each character in the string. I put a breakpoint and wrapped `cause` with `{ extra: { "cause": cause } }` and that appears to mitigate the issue but I'm not sure that this is desired. Any thoughts?

**Comment by adamduren** [comment]
I stumbled upon the official angular plugin and that seemed to solve the issue. Does this have any features the other does not?

**Comment by rebelliard** [comment]
The RavenJS API changed and this library is currently outdated. I have created a [fork](https://github.com/rebelliard/angular-raven/blob/v0.6.2/angular-raven.js#L145) which fixes the error, following the example of the RavenJS example.
