### ISSUE TITLE
Difference with the official Sentry plugin

### ISSUE THREAD

**Issue by karensg** [gdi2290/angular-raven#19]
I was wondering what is the actual difference with the official Angular support.
https://docs.getsentry.com/hosted/clients/javascript/integrations/angular/

So far I can see they work the same.

**Comment by giltotherescue** [comment]
The only difference I've been able to notice is the `development` flag. Which is actually useful. It's a shame there is no official development flag yet (at least not that I could find...).

**Comment by karensg** [comment]
Clear, you can implement the development flag with whitelisting of the domain, which makes this plugin not useful any more.
I am using the official implementation, works like a charm
